### ISSUE TITLE
Is it possible to generate slug with 8 or nine chars?

### ISSUE THREAD

**Issue by luiscoms** [necaris/cuid.py#10]
Once I generate a bunch of slugs, i need to increase the size of slug to be able to generate more of them.
Is it possible?
Thanks

**Comment by necaris** [comment]
In order to maintain API compatibility with [the specification and other implementations](https://github.com/ericelliott/cuid) I'm reluctant to change how `slug()` works. If you need a longer slug, why don't you use a full `cuid()`?

**Comment by luiscoms** [comment]
I see, I don`t want to use full cuid cause it is too long.

**Comment by necaris** [comment]
It sounds like you want to shorten the full cuid. If you simply take every 2nd or every 3rd character from the cuid, this will preserve other useful properties (like sorting) -- for example:
```python
>>> short_cuid = cuid.cuid()[::2]
>>> len(short_cuid) # 13
>>> shorter_cuid = cuid.cuid()[::3]
>>> len(shorter_cuid) # 9
```
If you're not so concerned about uniqueness, this should work.

**Comment by necaris** [comment]
Closing this issue since we have an alternative solution.
