### ISSUE TITLE
Failing to install due to non-ascii character and proposed a possible fix

### ISSUE THREAD

**Issue by zyli5313** [necaris/cuid.py#15]
Hi necaris,

the `μs` in README.md is a non ascii character which leads to failing to `pip install cuid.py` . You can refer to the sample bash output below. The details lies in the following pull request.

I proposed we fixed it by replacing `μs` with `us`.

I have submitted a [pull request](https://github.com/necaris/cuid.py/pull/14). If it looks good, could you please merge it?

Thanks,
Jake

**Comment by zyli5313** [comment]
Any suggestions?

**Comment by necaris** [comment]
Closing this as the PR is open: #14
