### ISSUE TITLE
Why the package name is cuid.py

### ISSUE THREAD

**Issue by notpushkin** [necaris/cuid.py#9]
And not just `cuid`? Looks like it's free on PyPI.

**Comment by necaris** [comment]
As it happened, just because it defaulted to the name of the repo when I uploaded it for the first time -- and note that the installed package _is_ named `cuid`. 

I'm happy to rename the package.

**Comment by ghost** [comment]
Please, add link to the documentation https://usecuid.org/
If it's the same one.

**Comment by necaris** [comment]
Closed by #11
